apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
  namespace: dev
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
      - name: MY_KEY
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: key
